#[derive(Clone, Copy, Eq, PartialEq, Debug)]
#[repr(u8)]
#[allow(dead_code)]
pub enum Command {
    Sleep = 0,
    Quit,
    InitDb,
    Query,
    FieldList,
    CreateDb,
    DropDb,
    Refresh,
    Deprecated1,
    Statistics,
    ProcessInfo,
    Connect,
    ProcessKill,
    Debug,
    Ping,
    Time,
    DelayedInsert,
    ChangeUser,
    BinlogDump,
    TableDump,
    ConnectOut,
    RegisterSlave,
    StmtPrepare,
    StmtExecute,
    StmtSendLongData,
    StmtClose,
    StmtReset,
    SetOption,
    StmtFetch,
    Daemon,
    BinlogDumpGTID,
    ResetConnection,
    End,
}
